name: Build and Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      working-directory: ./MP4_Player
      run: dotnet restore MP4_Player.csproj
    
    - name: Build
      working-directory: ./MP4_Player
      run: dotnet build MP4_Player.csproj -c Release --no-restore
    
    - name: Publish
      working-directory: ./MP4_Player
      run: dotnet publish MP4_Player.csproj -c Release -o ../publish
    
    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: Build ${{ github.run_number }}
        tag_name: v${{ github.run_number }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: publish/MP4_Player.exe
        asset_name: MP4_Player.exe
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ github.token }}
